name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/**"

jobs:
  main-job:
    name: Main job
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get base SHA
        id: base-sha
        run: |
          git fetch origin main --depth 1
          echo "sha=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT # SHA of master

      - name: Get changed utilities
        id: changed-utilities
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "${{ steps.base-sha.outputs.sha }}"
          dir_names: true
          dir_names_max_depth: 1
          path: utilities # only get changes in utilities folder

      - name: Setup python version 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy utilities
        if: ${{ steps.changed-utilities.outputs.any_changed == 'true' }}
        env:
          environment: Int
          bucket: tpg-ds
        run: |
          pip install --upgrade pip
          cd utilities
          python tester.py "${{ steps.changed-utilities.outputs.all_changed_files }}"
          while read p; do
            layer_name=$(echo $p | cut -d " " -f1)
            layer_dirs=$(echo $p | cut -d " " -f2-)
            python -m venv create_layer
            source create_layer/bin/activate
            IFS=' ' read -ra DIRS <<< $layer_dirs
            for dir_name in "${DIRS[@]}"; do
              pip install ./$dir_name
            done
            file_name="${{ github.sha }}.zip"
            zip -r9q $file_name create_layer/lib
            deactivate
            rm -r create_layer
            rm $file_name
          done <layers_to_build.txt