name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/tpds_utils/**"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Fetch main
        run: git fetch origin main --depth 1

      - name: Get Base SHA
        id: base-sha
        run: echo "sha=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "${{ steps.base-sha.outputs.sha }}"
          dir_names: true
          dir_names_max_depth: 1
          matrix: true
          path: utilities/tpds_utils

  deploy:
    name: Deploy to Int
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    env:
      full_path: "utilities/tpds_utils/${{ matrix.dir }}"
    steps:
      - name: Setup python version 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: checkout
        uses: actions/checkout@v4

      - name: create venv
        run: |
          pip install --upgrade pip
          python3.11 -m venv create_layer
          source create_layer/bin/activate
      
      - name: install requirements
        run: |
          pip install -r ${full_path}/requirements.txt

      - name: create layer zip file
        run: |
          mkdir python
          cp -r create_layer/lib python/
          rsync -av --exclude '${full_path}/requirements.txt' ${full_path} python/
          zip -r layer_content.zip python
      
      - name: upload the layer
        run: |
          aws lambda publish-layer-version --layer-name ${{ matrix.dir }} \
              --zip-file fileb://layer_content.zip \
              --compatible-runtimes python3.11 \
              --compatible-architectures "arm64"