name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/tpds_utils/**"

jobs:
  find-out-changes:
    name: Find out changes
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run:
          cd utilities/tpds_utils

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true

  deploy:
    name: Deploy to Int
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.dirs)}}
    needs:
      - find-out-changes

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: echo ${{ matrix.dir }}
