name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/tpds_utils/**"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Base SHA
        id: base-sha
        run: echo "sha=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "${{ steps.base-sha.outputs.sha }}"
          dir_names: true
          dir_names_max_depth: 1
          matrix: true
          path: utilities/tpds_utils
      
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  deploy:
    name: Deploy to Int
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: output directory
        run: echo ${{ matrix.dir }}
