name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/**"

jobs:
  main-job:
    name: Main job
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      environment: Int
      bucket: tpg-ds
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch master
        run: git fetch origin main --depth 1

      - name: Get base SHA
        id: base-sha
        run: echo "sha=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT # SHA of master

      - name: Get changed files
        id: changed-utilities
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "${{ steps.base-sha.outputs.sha }}"
          dir_names: true
          dir_names_max_depth: 1
          path: utilities # only get changes in utilities folder

      - name: Setup python version 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy utilities
        if: ${{ steps.changed-utilities.outputs.any_changed }} == 'true'
        env:
          environment: Int
          bucket: tpg-ds
        run: |
          echo ${{ steps.changed-utilities.outputs.any_changed }}
          pip install --upgrade pip
          IFS=' ' read -ra DIRS <<< "${{ steps.changed-utilities.outputs.all_changed_files }}"
          for dir_name in "${DIRS[@]}"; do
            cd utilities/$dir_name
            file_name="$(cat version.txt).zip"
            python3.11 -m venv create_layer
            source create_layer/bin/activate
            pip install -r requirements.txt
            mkdir python
            cp -r create_layer/lib python/
            rsync -av --exclude-from='exclude_list.txt' --exclude python --exclude create_layer . python
            zip -r $file_name python
            S3_key=$environment/layers/$dir_name/$file_name
            # aws s3 cp $file_name s3://$bucket/$S3_key
            # aws lambda publish-layer-version --layer-name $dir_name \
            #     --content S3Bucket=$bucket,S3Key=$S3_key \
            #     --compatible-runtimes python3.11 \
            #     --compatible-architectures "arm64"
            cd ../../
          done