name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/tpds_utils/**"

jobs:
  find-out-changes:
    name: Find out changes
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Change directory to tpds_utils
        run: cd utilities/tpds_utils

      - name: Base SHA
        id: base-sha
        run: echo "sha=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "${{ steps.base-sha.outputs.sha }}"
          dir_names: true
          dir_names_max_depth: 3
          matrix: true
          quotepath: false
      
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  deploy:
    name: Deploy to Int
    runs-on: ubuntu-latest
    needs: [find-out-changes]
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: output directory
        run: echo ${{ matrix.dir }}
