name: Int - Deploy Utils to Lambda

on:
  push:
    tags:
      - "util*"
    paths:
      - "utilities/tpds_utils/**"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      utilities_changed: ${{ steps.changed-utilities.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch master
        run: git fetch origin master --depth 1

      - name: Get base SHA
        id: base-sha
        run: echo "sha=$(git rev-parse origin/master)" >> $GITHUB_OUTPUT # SHA of master

      - name: Get changed files
        id: changed-utilities
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "${{ steps.base-sha.outputs.sha }}"
          dir_names: true
          dir_names_max_depth: 1
          matrix: true
          path: utilities # only get changes in utilities folder

  deploy:
    name: Deploy to Int
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [changed-files]
        if: ${{ needs.changed-files.outputs.utilities_changed != '[]' }}  # Without it, the strategy parser will fail if the matrix is empty.
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changed-files.outputs.utilities_changed) }}
      max-parallel: 4
      fail-fast: false
    env:
      full_path: "utilities/${{ matrix.dir }}"
    steps:
      - name: Setup python version 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create venv
        run: |
          pip install --upgrade pip
          python3.11 -m venv create_layer
          source create_layer/bin/activate
      
      - name: Install requirements
        run: |
          pip install -r ${full_path}/requirements.txt

      - name: Create layer zip file
        run: |
          mkdir python
          cp -r create_layer/lib python/
          rsync -av --exclude '${full_path}/requirements.txt' ${full_path} python/
          zip -r layer_content.zip python
      
      - name: Configure tpg_main credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::606105707499:role/TpdsBuildDeployRole
          aws-region: us-west-2
      
      - name: Upload the layer
        run: |
          aws lambda publish-layer-version --layer-name ${{ matrix.dir }} \
              --zip-file fileb://layer_content.zip \
              --compatible-runtimes python3.11 \
              --compatible-architectures "arm64"